remote_theme: chrisbobbe/jekyll-theme-prologue

collections: [docs]

repository_links:
  enabled: false
page_navigator:
  enabled: false
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project.

title: "Project Card Combat (Title work in progress)"
description: "A quick, fun, PvE card game"
author:
  name: "Robert Dominguez"
  